/*
 * Copyright 2015 Jacob Nordfalk
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 */
package apertiumview;

/**
 *
 * @author Jacob Nordfalk
 */
public class OptionsPanel extends javax.swing.JPanel {

    /** Creates new form OptionsPanel */
	public OptionsPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        envVarsTextArea = new javax.swing.JTextArea();
        ignoreErrorMessages = new javax.swing.JCheckBox();
        externalProcessing = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        workingDirTextField = new javax.swing.JTextField();

        envVarsTextArea.setColumns(20);
        envVarsTextArea.setRows(5);
        jScrollPane1.setViewportView(envVarsTextArea);

        ignoreErrorMessages.setLabel("Ignore error messages from commands");

        externalProcessing.setText("Use external processing");
        externalProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalProcessingActionPerformed(evt);
            }
        });

        jLabel1.setText("Working directory (leave empty to use default)");

        jLabel2.setText("<html>Environment variables  (leave empty to use default)<br>\nExample: \nLANG=en_US.UTF-8");

        workingDirTextField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(workingDirTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(ignoreErrorMessages)
                    .addComponent(externalProcessing))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(externalProcessing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workingDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ignoreErrorMessages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  private void externalProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalProcessingActionPerformed
       setExternalProcessingOptionsEnabled(externalProcessing.isSelected());
    }//GEN-LAST:event_externalProcessingActionPerformed

    public void setExternalProcessingOptionsEnabled(boolean b) {
        envVarsTextArea.setEnabled(b);
        ignoreErrorMessages.setEnabled(b);
        jLabel1.setEnabled(b);
        jLabel2.setEnabled(b);
        jScrollPane1.setEnabled(b);
        workingDirTextField.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextArea envVarsTextArea;
    javax.swing.JCheckBox externalProcessing;
    public javax.swing.JCheckBox ignoreErrorMessages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField workingDirTextField;
    // End of variables declaration//GEN-END:variables

}
