all:
	#latex mtsxivslsh
	#bibtex mtsxivslsh
	#latex mtsxivslsh
	#latex mtsxivslsh
	pdflatex mtsxivslsh
clean:
	rm mtsxivslsh.aux mtsxivslsh.dvi mtsxivslsh.pdf mtsxivslsh.blg mtsxivslsh.bbl mtsxivslsh.log
