coverage:
  ast: 0.0
  bg: 0.68835
  bn: 0.7529
  br: 0.70195
  ca: 0.6891
  en: 0.77
  zh: 0.77485
langs:
  ast: /home/wei2912/corpus/ast/wiki-20140520.txt.norm
  bg: /home/wei2912/corpus/bg/wiki-20140506.txt.norm
  bn: /home/wei2912/corpus/bn/wiki-20140514.txt.norm
  br: /home/wei2912/corpus/br/wiki-20140520.txt.norm
  ca: /home/wei2912/corpus/ca/wiki-20140515.txt.norm
  en: /home/wei2912/corpus/en/wiki-20140502.txt.norm
  zh: /home/wei2912/corpus/zh/wiki-20140508.txt.norm
