/*
 * Copyright 2015 Jacob Nordfalk
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 */
package apertiumview;

/**
 *
 * @author Jacob Nordfalk
 */
public class OptionsPanel extends javax.swing.JPanel {

    /** Creates new form OptionsPanel */
    public OptionsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        envVarsTextArea = new javax.swing.JTextArea();
        workingDirTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ignoreErrorMessages = new javax.swing.JCheckBox();
        externalProcessing = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        envVarsTextArea.setColumns(20);
        envVarsTextArea.setRows(5);
        envVarsTextArea.setName("envVarsTextArea"); // NOI18N
        jScrollPane1.setViewportView(envVarsTextArea);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(apertiumview.ApertiumViewMain.class).getContext().getResourceMap(OptionsPanel.class);
        workingDirTextField.setText(resourceMap.getString("workingDirTextField.text")); // NOI18N
        workingDirTextField.setName("workingDirTextField"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        ignoreErrorMessages.setLabel(resourceMap.getString("ignoreErrorMessages.label")); // NOI18N

        externalProcessing.setText(resourceMap.getString("externalProcessing.text")); // NOI18N
        externalProcessing.setName("externalProcessing"); // NOI18N
        externalProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalProcessingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(workingDirTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(ignoreErrorMessages)
                    .addComponent(externalProcessing))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(externalProcessing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workingDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ignoreErrorMessages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void externalProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalProcessingActionPerformed
        setExternalProcessingOptionsEnabled(externalProcessing.isSelected());
    }//GEN-LAST:event_externalProcessingActionPerformed

    public void setExternalProcessingOptionsEnabled(boolean b) {
        envVarsTextArea.setEnabled(b);
        ignoreErrorMessages.setEnabled(b);
        jLabel1.setEnabled(b);
        jLabel2.setEnabled(b);
        jScrollPane1.setEnabled(b);
        workingDirTextField.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextArea envVarsTextArea;
    javax.swing.JCheckBox externalProcessing;
    public javax.swing.JCheckBox ignoreErrorMessages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField workingDirTextField;
    // End of variables declaration//GEN-END:variables

}
